apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment # this will be the deployment name
  labels:
    app: helloyoufrontend
spec:
  replicas: 2 # number of pods to be created
  selector:
    matchLabels:
      app: helloyoufrontend # have this matched with metadata.labels.app
  template:
    metadata:
      labels:
        app: helloyoufrontend # have this matched with metadata.labels.app
    spec:
      containers:
        - name: myhello-project
          image: kleydocker/myhello_project:1.1
