apiVersion: v1
kind: Service
metadata:
  name: hello-service # this will be the service name
spec:
  #type: NodePort
  selector:
    app: helloyoufrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
